"""Memory Provider Port、Registry 与测试替身。"""

from core.memory_provider.contracts import (
    ALL_MEMORY_PROVIDER_CAPABILITIES,
    MemoryCompactionContext,
    MemoryDelegationContext,
    MemoryPrefetchContext,
    MemoryPromptBlock,
    MemoryPromptContext,
    MemoryProviderCapability,
    MemoryProviderDescriptor,
    MemoryProviderDiagnostic,
    MemoryProviderFailurePolicy,
    MemoryProviderInitContext,
    MemoryProviderPort,
    MemoryRequestContext,
    MemorySessionContext,
    MemorySyncTurnContext,
    MemoryToolCall,
    MemoryToolSchemaContext,
)
from core.memory_provider.fake import FakeMemoryProvider
from core.memory_provider.registry import (
    MemoryProviderContractError,
    MemoryProviderDependencyError,
    MemoryProviderFactory,
    MemoryProviderRegistration,
    MemoryProviderRegistry,
    MemoryProviderRegistryError,
    MemoryProviderRuntime,
)

__all__ = [
    "ALL_MEMORY_PROVIDER_CAPABILITIES",
    "FakeMemoryProvider",
    "MemoryCompactionContext",
    "MemoryDelegationContext",
    "MemoryPrefetchContext",
    "MemoryPromptBlock",
    "MemoryPromptContext",
    "MemoryProviderCapability",
    "MemoryProviderContractError",
    "MemoryProviderDependencyError",
    "MemoryProviderDescriptor",
    "MemoryProviderDiagnostic",
    "MemoryProviderFactory",
    "MemoryProviderFailurePolicy",
    "MemoryProviderInitContext",
    "MemoryProviderPort",
    "MemoryProviderRegistration",
    "MemoryProviderRegistry",
    "MemoryProviderRegistryError",
    "MemoryProviderRuntime",
    "MemoryRequestContext",
    "MemorySessionContext",
    "MemorySyncTurnContext",
    "MemoryToolCall",
    "MemoryToolSchemaContext",
]
