"""Nanobot 离线语义回放、A/B 对比与故障注入。"""

from core.replay.contracts import (
    FrozenEvent,
    FrozenModelResponse,
    FrozenReplayFixture,
    FrozenToolOutcome,
    REQUIRED_FAULT_KINDS,
    ReplayComponentRef,
    ReplayContractError,
    ReplayFault,
    ReplayFaultKind,
    ReplayScript,
    ReplayStatus,
    ReplayUsage,
    ReplayVariant,
    initial_replay_state,
    model_request_sha256,
    parse_faults,
    sha256_json,
)
from core.replay.engine import (
    FrozenModelSubstitute,
    FrozenToolSubstitute,
    ReplayComparisonReport,
    ReplayRunReport,
    ReplaySafetyError,
    compare_replays,
    default_faults,
    run_fault_matrix,
    run_replay,
)


__all__ = [
    "FrozenEvent",
    "FrozenModelResponse",
    "FrozenModelSubstitute",
    "FrozenReplayFixture",
    "FrozenToolOutcome",
    "FrozenToolSubstitute",
    "REQUIRED_FAULT_KINDS",
    "ReplayComparisonReport",
    "ReplayComponentRef",
    "ReplayContractError",
    "ReplayFault",
    "ReplayFaultKind",
    "ReplayRunReport",
    "ReplaySafetyError",
    "ReplayScript",
    "ReplayStatus",
    "ReplayUsage",
    "ReplayVariant",
    "compare_replays",
    "default_faults",
    "initial_replay_state",
    "model_request_sha256",
    "parse_faults",
    "run_fault_matrix",
    "run_replay",
    "sha256_json",
]
