"""Rolling Session Summary 配置常量。"""

PRIVATE_RAW_WINDOW_MAX_TURNS = 32
PRIVATE_RAW_WINDOW_MAX_TOKENS = 4000
PRIVATE_ROLLING_MIN_TURNS = 6
PRIVATE_ROLLING_MIN_USER_TURNS = 2
PRIVATE_ROLLING_MIN_CHARS = 1200
PRIVATE_ROLLING_MIN_TOKENS = 800

GROUP_RAW_WINDOW_MAX_TURNS = 10
GROUP_RAW_WINDOW_MAX_TOKENS = 2500
GROUP_ROLLING_MIN_TURNS = 10
GROUP_ROLLING_MIN_USER_TURNS = 4
GROUP_ROLLING_MIN_DISTINCT_SENDERS = 2
GROUP_ROLLING_MIN_CHARS = 1800
GROUP_ROLLING_MIN_TOKENS = 1200

ROLLING_SUMMARY_MAX_CHARS = 1800
ROLLING_SUMMARY_ENABLED = True

SESSION_SUMMARY_LLM_ENABLED = True
SESSION_SUMMARY_LLM_ASYNC_ONLY = True
SESSION_SUMMARY_JOB_BATCH_SIZE = 10
SESSION_SUMMARY_MAX_RETRY = 3
SESSION_SUMMARY_RETRY_DELAY_SEC = 300
SESSION_SUMMARY_RUNNING_TIMEOUT_SEC = 900
# 旧输入/单 turn 常量只保留兼容；LLM 编排使用下面三个完整请求合同常量。
SESSION_SUMMARY_LLM_MAX_INPUT_CHARS = 12000
SESSION_SUMMARY_LLM_MAX_TURN_CHARS = 12000
# 近期摘要的 JSON 合同包含业务字段、quality 与 inheritance 审计信息。
# 该上限按紧凑 JSON 计算；排版空白不计入容量。
SESSION_SUMMARY_LLM_MAX_OUTPUT_CHARS = 6000
SESSION_SUMMARY_LLM_MAX_REQUEST_CHARS = 12000
SESSION_SUMMARY_LLM_MAX_STATE_CHARS = 4000
SESSION_SUMMARY_LLM_REQUEST_SAFETY_CHARS = 512
SESSION_SUMMARY_FALLBACK_ENABLED = True

# ── 块式会话记忆(Block Session Memory) ──
# 见 docs/superpowers/specs/2026-07-26-block-session-memory-design.md。
# canonical 开关是 settings 键 block_memory.enabled(env NANOBOT_BLOCK_MEMORY_ENABLED,
# 管理端可运行时改)+ block_memory.session_allowlist 灰度白名单;统一入口
# app/session_memory/blocks.py::is_block_memory_enabled。本常量仅作 settings
# 服务不可用时的最后兜底,保持 False。
BLOCK_SESSION_MEMORY_ENABLED = False
# 相邻 user 消息间隔达到该秒数则封口开新块;与块内 CONTEXT_GAP_HINT_MIN(视觉
# 时间间隔提示)正交,BLOCK_GAP_SECONDS 必须大于后者。
BLOCK_GAP_SECONDS = 1800
# open 块静默超过该秒数由 idle sweep 兜底封口(P4);须 >= BLOCK_GAP_SECONDS。
BLOCK_IDLE_SEAL_SECONDS = 7200
# 单块尺寸上限;任一超限即封口开新块,防止长连续对话把块撑到无法召回。
BLOCK_MAX_TURNS = 200
BLOCK_MAX_TOKENS = 16000
