"""Rolling Session Summary 配置常量。"""

PRIVATE_RAW_WINDOW_MAX_TURNS = 32
PRIVATE_RAW_WINDOW_MAX_TOKENS = 4000
PRIVATE_ROLLING_MIN_TURNS = 6
PRIVATE_ROLLING_MIN_USER_TURNS = 2
PRIVATE_ROLLING_MIN_CHARS = 1200
PRIVATE_ROLLING_MIN_TOKENS = 800

GROUP_RAW_WINDOW_MAX_TURNS = 10
GROUP_RAW_WINDOW_MAX_TOKENS = 2500
GROUP_ROLLING_MIN_TURNS = 10
GROUP_ROLLING_MIN_USER_TURNS = 4
GROUP_ROLLING_MIN_DISTINCT_SENDERS = 2
GROUP_ROLLING_MIN_CHARS = 1800
GROUP_ROLLING_MIN_TOKENS = 1200

ROLLING_SUMMARY_MAX_CHARS = 1800
ROLLING_SUMMARY_ENABLED = True

SESSION_SUMMARY_LLM_ENABLED = True
SESSION_SUMMARY_LLM_ASYNC_ONLY = True
SESSION_SUMMARY_JOB_BATCH_SIZE = 10
SESSION_SUMMARY_MAX_RETRY = 3
SESSION_SUMMARY_RETRY_DELAY_SEC = 300
SESSION_SUMMARY_RUNNING_TIMEOUT_SEC = 900
SESSION_SUMMARY_LLM_MAX_INPUT_CHARS = 12000
SESSION_SUMMARY_LLM_MAX_TURN_CHARS = 12000
SESSION_SUMMARY_LLM_MAX_OUTPUT_CHARS = 1800
SESSION_SUMMARY_PROMOTE_MIN_SCORE = 0.7
SESSION_SUMMARY_FALLBACK_ENABLED = True
