"""Rolling Session Summary 配置常量。"""

# Prompt Cache epoch 内只追加；超过高水位后一次性摘要，并回落到低水位。
PRIVATE_CACHE_EPOCH_LOW_WATER_TURNS = 32
PRIVATE_CACHE_EPOCH_HIGH_WATER_TURNS = 40
PRIVATE_CACHE_EPOCH_LOW_WATER_TOKENS = 4000
PRIVATE_CACHE_EPOCH_HIGH_WATER_TOKENS = 8000
# 旧名称保留给兼容调用方，语义为 epoch 重建后的低水位。
PRIVATE_RAW_WINDOW_MAX_TURNS = PRIVATE_CACHE_EPOCH_LOW_WATER_TURNS
PRIVATE_RAW_WINDOW_MAX_TOKENS = PRIVATE_CACHE_EPOCH_LOW_WATER_TOKENS
PRIVATE_CONTEXT_MAX_MESSAGE_CHARS = 2200
PRIVATE_ROLLING_MIN_TURNS = 6
PRIVATE_ROLLING_MIN_USER_TURNS = 2
PRIVATE_ROLLING_MIN_CHARS = 1200
PRIVATE_ROLLING_MIN_TOKENS = 800

# 旧 ConversationTurn 群聊入口仍由 should_rollup() 使用；真实群聊摘要发现
# 已迁移到下面的 ChatLog token 阈值，不复用这些兼容常量。
GROUP_ROLLING_MIN_TURNS = 10
GROUP_ROLLING_MIN_USER_TURNS = 4
GROUP_ROLLING_MIN_DISTINCT_SENDERS = 2
GROUP_ROLLING_MIN_CHARS = 1800
GROUP_ROLLING_LEGACY_MIN_TOKENS = 1200

# 群聊 Rolling Summary 只由后台 worker 驱动。回复链路保留最新约 6000
# tokens 原文；更早内容达到软/硬阈值后，按 ChatLog 游标连续归入摘要。
GROUP_CACHE_EPOCH_LOW_WATER_TOKENS = 6000
GROUP_CACHE_EPOCH_HIGH_WATER_TOKENS = 16000
GROUP_RAW_WINDOW_MAX_TOKENS = GROUP_CACHE_EPOCH_LOW_WATER_TOKENS
GROUP_ROLLING_MIN_TOKENS = 8000
# 旧 pending-only 阈值仅保留兼容；触发事实以 epoch 总 tokens 高水位为准。
GROUP_ROLLING_FORCE_TOKENS = (
    GROUP_CACHE_EPOCH_HIGH_WATER_TOKENS
    - GROUP_CACHE_EPOCH_LOW_WATER_TOKENS
)
GROUP_ROLLING_COOLDOWN_SECONDS = 15 * 60
GROUP_ROLLING_IDLE_SECONDS = 60
GROUP_ROLLING_JOB_MAX_TOKENS = 16000
GROUP_CONTEXT_MAX_TOKENS = 24000
GROUP_CONTEXT_MAX_MESSAGE_CHARS = 12000
# 无摘要兜底超过上下文预算时，最老边界按固定 ChatLog ID 块轮换，避免每条
# 新消息都移动缓存前缀；正常 6000 tokens 原文窗口不会触发该裁剪。
GROUP_CONTEXT_SOURCE_ID_BLOCK_SPAN = 8
GROUP_SUMMARY_DISCOVERY_BATCH_SIZE = 100
# 同一摘要合同失败后，后台扫描只允许一次有界自动恢复；恢复前保留冷却，
# 避免扫描热循环不断创建等价任务。管理端显式 retry 不受该门禁限制。
GROUP_SUMMARY_AUTO_RECOVERY_MAX = 1
GROUP_SUMMARY_FAILURE_COOLDOWN_SECONDS = 15 * 60
# 仅供旧 ConversationTurn 辅助入口兼容；真实群聊链路不按消息条数裁剪。
GROUP_RAW_WINDOW_MAX_TURNS = 5000

ROLLING_SUMMARY_MAX_CHARS = 1800
ROLLING_SUMMARY_ENABLED = True

SESSION_SUMMARY_LLM_ENABLED = True
SESSION_SUMMARY_LLM_ASYNC_ONLY = True
SESSION_SUMMARY_JOB_BATCH_SIZE = 10
SESSION_SUMMARY_MAX_RETRY = 3
SESSION_SUMMARY_RETRY_DELAY_SEC = 300
SESSION_SUMMARY_RUNNING_TIMEOUT_SEC = 900
# 旧输入/单 turn 常量只保留兼容；LLM 编排使用下面三个完整请求合同常量。
SESSION_SUMMARY_LLM_MAX_INPUT_CHARS = 12000
SESSION_SUMMARY_LLM_MAX_TURN_CHARS = 12000
# 近期摘要的 JSON 合同包含业务字段、quality 与 inheritance 审计信息。
# 该上限按紧凑 JSON 计算；排版空白不计入容量。
SESSION_SUMMARY_LLM_MAX_OUTPUT_CHARS = 6000
# 群聊单个摘要 job 最多约 16000 tokens。请求预算必须容纳这一完整 coverage，
# 避免按 5k tokens 左右反复切批、让中间摘要在同一任务内持续膨胀。
SESSION_SUMMARY_LLM_MAX_REQUEST_CHARS = 192000
SESSION_SUMMARY_LLM_MAX_STATE_CHARS = 4000
SESSION_SUMMARY_LLM_REQUEST_SAFETY_CHARS = 512
SESSION_SUMMARY_FALLBACK_ENABLED = True

# ── 块式会话记忆(Block Session Memory) ──
# 见 docs/superpowers/specs/2026-07-26-block-session-memory-design.md。
# canonical 开关是 settings 键 block_memory.enabled(env NANOBOT_BLOCK_MEMORY_ENABLED,
# 管理端可运行时改)+ block_memory.session_allowlist 灰度白名单;统一入口
# app/session_memory/blocks.py::is_block_memory_enabled。本常量仅作 settings
# 服务不可用时的最后兜底,保持 False。
BLOCK_SESSION_MEMORY_ENABLED = False
# 相邻 user 消息间隔达到该秒数则封口开新块;与块内 CONTEXT_GAP_HINT_MIN(视觉
# 时间间隔提示)正交,BLOCK_GAP_SECONDS 必须大于后者。
BLOCK_GAP_SECONDS = 1800
# open 块静默超过该秒数由 idle sweep 兜底封口(P4);须 >= BLOCK_GAP_SECONDS。
BLOCK_IDLE_SEAL_SECONDS = 7200
# 单块尺寸上限;任一超限即封口开新块,防止长连续对话把块撑到无法召回。
BLOCK_MAX_TURNS = 200
BLOCK_MAX_TOKENS = 16000
