"""Nanobot 运行时横切合同。"""

from core.runtime.events import (
    InMemoryRuntimeEventSink,
    RuntimeEvent,
    RuntimeEventContext,
    RuntimeEventDescriptor,
    RuntimeEventEmitter,
    RuntimeEventField,
    RuntimeEventRegistry,
    RuntimeEventRegistryError,
    RuntimeEventSink,
)
from core.runtime.extensions import (
    PROTECTED_TRANSFORM_INVARIANTS,
    PolicyDescriptor,
    PolicyExecutionResult,
    PolicyFailureCode,
    PolicyFailureOutcome,
    RuntimeExtensionKind,
    RuntimeFailurePolicy,
    RuntimeHookDescriptor,
    RuntimeHookFailureCode,
    RuntimeHookRegistry,
    RuntimeObserverBinding,
    RuntimeObserverDispatcher,
    RuntimeTransformBinding,
    RuntimeTransformDispatcher,
    execute_policy,
)

__all__ = [
    "InMemoryRuntimeEventSink",
    "PROTECTED_TRANSFORM_INVARIANTS",
    "PolicyDescriptor",
    "PolicyExecutionResult",
    "PolicyFailureCode",
    "PolicyFailureOutcome",
    "RuntimeEvent",
    "RuntimeEventContext",
    "RuntimeEventDescriptor",
    "RuntimeEventEmitter",
    "RuntimeEventField",
    "RuntimeEventRegistry",
    "RuntimeEventRegistryError",
    "RuntimeEventSink",
    "RuntimeExtensionKind",
    "RuntimeFailurePolicy",
    "RuntimeHookDescriptor",
    "RuntimeHookFailureCode",
    "RuntimeHookRegistry",
    "RuntimeObserverBinding",
    "RuntimeObserverDispatcher",
    "RuntimeTransformBinding",
    "RuntimeTransformDispatcher",
    "execute_policy",
]
