"""统一语义 Task Runtime 的公共合同。"""

from core.task_runtime.contracts import (
    TaskFailureCode,
    TaskFailureStage,
    TaskInvocation,
    TaskModelCompletion,
    TaskModelExecutionError,
    TaskModelExecutionPort,
    TaskModelRequest,
    TaskResult,
    TaskTerminalAction,
    TaskTypedFailure,
    TaskValidationDiagnostic,
    failure_category_for_code,
    thaw_task_value,
)
from core.task_runtime.resilience import (
    RESILIENCE_POLICY_REGISTRY,
    ResiliencePolicyDescriptor,
    ResiliencePolicyRegistry,
    list_resilience_policies,
    require_resilience_policy,
)
from core.resilience import FailureCategory
from core.task_runtime.runtime import (
    TaskRuntime,
    TaskRuntimeState,
    execute_task,
    start_task_runtime,
    stop_task_runtime,
    task_runtime_status,
)
from core.task_runtime.slo import (
    TASK_SLO_REGISTRY,
    TaskBillingClass,
    TaskSloActivationError,
    TaskSloDescriptor,
    TaskSloRegistry,
    TaskSloStatus,
    get_task_slo_descriptor,
    require_task_slo_activation,
    require_task_slo_descriptor,
)

__all__ = [
    "ResiliencePolicyDescriptor",
    "ResiliencePolicyRegistry",
    "RESILIENCE_POLICY_REGISTRY",
    "FailureCategory",
    "TaskFailureCode",
    "TaskFailureStage",
    "TaskInvocation",
    "TaskModelCompletion",
    "TaskModelExecutionError",
    "TaskModelExecutionPort",
    "TaskModelRequest",
    "TaskResult",
    "TaskRuntime",
    "TaskRuntimeState",
    "TASK_SLO_REGISTRY",
    "TaskBillingClass",
    "TaskSloActivationError",
    "TaskSloDescriptor",
    "TaskSloRegistry",
    "TaskSloStatus",
    "TaskTerminalAction",
    "TaskTypedFailure",
    "TaskValidationDiagnostic",
    "execute_task",
    "failure_category_for_code",
    "get_task_slo_descriptor",
    "list_resilience_policies",
    "require_resilience_policy",
    "require_task_slo_activation",
    "require_task_slo_descriptor",
    "start_task_runtime",
    "stop_task_runtime",
    "task_runtime_status",
    "thaw_task_value",
]
