"""声明式 Agent Manifest 稳定合同。"""

from .contracts import AgentManifest
from .compiler import (
    AgentManifestCompilationError,
    CompiledAgentSnapshot,
    compile_agent_manifest,
)
from .preflight import (
    AgentBudgetCeilings,
    AgentDiagnosticSeverity,
    AgentExportedName,
    AgentExportNamespace,
    AgentExtensionCatalog,
    AgentExtensionCatalogEntry,
    AgentManifestCompilationEnvironment,
    AgentManifestDiagnostic,
    AgentModelRouteSnapshot,
    AgentPinnedResourceKind,
    AgentPinnedResourceSnapshot,
    AgentSecurityPreflightSnapshot,
    AgentWorkspacePreflightSnapshot,
)
from .values import (
    AgentBudget,
    AgentEvaluationPolicy,
    AgentExtensionKind,
    AgentExtensionRef,
    AgentExtensionSet,
    AgentHookEvent,
    AgentHookRef,
    AgentIdentity,
    AgentModelSpec,
    AgentOutputContractRef,
    AgentPermissionSpec,
    AgentPromptBundleRef,
    AgentRolloutPolicy,
    AgentRuntimeSpec,
    AgentSecretRef,
    AgentSourceKind,
    AgentSourceRef,
    AgentStatePolicy,
)


__all__ = [
    "AgentBudget",
    "AgentBudgetCeilings",
    "AgentDiagnosticSeverity",
    "AgentEvaluationPolicy",
    "AgentExportedName",
    "AgentExportNamespace",
    "AgentExtensionCatalog",
    "AgentExtensionCatalogEntry",
    "AgentExtensionKind",
    "AgentExtensionRef",
    "AgentExtensionSet",
    "AgentHookEvent",
    "AgentHookRef",
    "AgentIdentity",
    "AgentManifest",
    "AgentManifestCompilationEnvironment",
    "AgentManifestCompilationError",
    "AgentManifestDiagnostic",
    "AgentModelSpec",
    "AgentModelRouteSnapshot",
    "AgentOutputContractRef",
    "AgentPinnedResourceKind",
    "AgentPinnedResourceSnapshot",
    "AgentPermissionSpec",
    "AgentPromptBundleRef",
    "AgentRolloutPolicy",
    "AgentRuntimeSpec",
    "AgentSecurityPreflightSnapshot",
    "AgentSecretRef",
    "AgentSourceKind",
    "AgentSourceRef",
    "AgentStatePolicy",
    "AgentWorkspacePreflightSnapshot",
    "CompiledAgentSnapshot",
    "compile_agent_manifest",
]
