"""主动外呼静态策略常量。"""

from __future__ import annotations

from core.proactive_candidate import (
    DEFAULT_MAX_CHECK_INTERVAL_MIN,
    DEFAULT_MAX_SILENCE_MIN,
    DEFAULT_MIN_INTERVAL_MIN,
    DEFAULT_SURGE_MAX_PROB,
    DEFAULT_SURGE_MIN_PROB,
)


DEFAULT_EVALUATION_LEASE_SECONDS = 900
DEFAULT_SENDING_AMBIGUITY_MINUTES = 30
DEFAULT_AMBIGUOUS_HOLD_MIN = 120
KNOWN_OUTREACH_STATES = frozenset({
    "pending",
    "candidate",
    "sending",
    "queued",
    "delivering",
    "retry_wait",
    "sent",
    "sent_after_ambiguous_replay",
    "failed",
    "blocked",
    "evaluation_error",
    "ambiguous",
    "cancelled",
    "legacy_ambiguous_hold",
})
OUTREACH_SOURCE_TYPE = "proactive_outreach"
OUTREACH_ENDPOINT_KEY = "qq_push"
OUTREACH_PAYLOAD_CONTRACT = "qq-envelope-v1"
OUTREACH_CLAIM_LEASE_SECONDS = 900.0
OUTREACH_WRITER_LEASE_SECONDS = 900.0
OUTREACH_DEFAULT_MAX_ATTEMPTS = 3
OUTREACH_DEFAULT_RETRY_DEADLINE_SECONDS = 86400.0
OUTREACH_SCHEDULER_POLL_SECONDS = 60.0
DEFAULT_REPEAT_TOPIC_COOLDOWN_MIN = 1440


__all__ = [
    "DEFAULT_AMBIGUOUS_HOLD_MIN",
    "DEFAULT_EVALUATION_LEASE_SECONDS",
    "DEFAULT_MAX_CHECK_INTERVAL_MIN",
    "DEFAULT_MAX_SILENCE_MIN",
    "DEFAULT_MIN_INTERVAL_MIN",
    "DEFAULT_REPEAT_TOPIC_COOLDOWN_MIN",
    "DEFAULT_SENDING_AMBIGUITY_MINUTES",
    "DEFAULT_SURGE_MAX_PROB",
    "DEFAULT_SURGE_MIN_PROB",
    "KNOWN_OUTREACH_STATES",
    "OUTREACH_CLAIM_LEASE_SECONDS",
    "OUTREACH_DEFAULT_MAX_ATTEMPTS",
    "OUTREACH_DEFAULT_RETRY_DEADLINE_SECONDS",
    "OUTREACH_ENDPOINT_KEY",
    "OUTREACH_PAYLOAD_CONTRACT",
    "OUTREACH_SCHEDULER_POLL_SECONDS",
    "OUTREACH_SOURCE_TYPE",
    "OUTREACH_WRITER_LEASE_SECONDS",
]
