"""数据库兼容 façade。

新代码应从 ``core.db``、具体 ``core.db.models`` 或领域 Repository Port
导入。该模块只为历史导入路径重导出 Session 基础设施和 ORM 模型。
"""

import os

from config import DATABASE_URL
from core.db.base import Base
from core.db.models import (
    AdminAuditLog,
    AdminIdempotencyRecord,
    AgentRun,
    Asset,
    ChatDeliveryOutbox,
    ChatLog,
    ChatStreamConfig,
    ContentBlockRule,
    ConversationBlock,
    ConversationBlockEpisode,
    ConversationTurn,
    EvalCandidate,
    EvalRun,
    EvalRunResult,
    EvalSampleCursor,
    ExpressionMemory,
    GroupLearningCandidate,
    GroupLearningEvidence,
    GroupLearningRun,
    GroupLearningSchedule,
    GroupLearningStreamState,
    GroupMemory,
    InboundMessageClaim,
    JargonMemory,
    KnowledgeChunk,
    KnowledgeDocument,
    KnowledgeSource,
    LLMApiRequestLog,
    MemoryCleanupRun,
    MemoryDigest,
    MemoryDigestJob,
    McpConfigurationStateRow,
    McpDiagnosticRow,
    McpSecretRow,
    McpServerRow,
    OutboundDeliveryAttempt,
    OutboundDeliveryCircuit,
    OutboundDeliveryControl,
    OutboundDeliveryOutbox,
    OutboundGenerationAttempt,
    OutboundRun,
    Persona,
    PersonaBehavior,
    PersonaFact,
    ProactiveOutreachLease,
    ProactiveOutreachLog,
    PromptFileVersion,
    PromptRenderLog,
    RagDebugRun,
    ReplyContractCheckLog,
    ReplyEvalCase,
    ReplyEvalResult,
    ReplyEvalRun,
    RollingSessionSummary,
    RuntimeTelemetryEvent,
    RuntimeToolDecision,
    RunLedgerErasureAuthorization,
    RunLedgerErasureReceipt,
    RunLedgerEventRow,
    RunLedgerLegalHold,
    RunLedgerStreamHead,
    RunCheckpointRow,
    RunRecoveryOperation,
    RunSideEffectReceipt,
    RunTaskControl,
    SANDBOX_EXECUTION_PROFILES,
    SANDBOX_LEASE_NONTERMINAL_STATUSES,
    SANDBOX_LEASE_STATUSES,
    SANDBOX_LEASE_TERMINAL_STATUSES,
    SandboxAccessGrant,
    SandboxAdminOperation,
    SandboxControllerState,
    SandboxLease,
    SandboxProjectSequence,
    SandboxRun,
    ScheduledTask,
    ScheduledTaskExecution,
    ScheduledTaskOwnerLease,
    ScheduledTaskStepAttempt,
    SemanticIndexItem,
    SemanticIndexJob,
    SensitiveData,
    SessionSummaryJob,
    SessionGoalEventRow,
    SessionGoalRow,
    SessionPlanAssetRow,
    SkillBindingRow,
    SkillEvaluationRow,
    SkillInvocationRow,
    SkillLifecycleEventRow,
    SkillPackageFileRow,
    SkillPackageRow,
    StickerDuplicateCandidate,
    StickerMemory,
    SystemPrompt,
    SystemSetting,
    ToolCall,
    ToolOverride,
    User,
    UserBlockRule,
    WebSearchProviderUsage,
    Workspace,
    WorkspaceAsset,
    WorkspaceMaintenanceState,
    WorkspaceQuotaBinding,
    WorkspaceRuntimeQuotaBinding,
)
from core.db.session import (
    DB_DIR,
    DB_PATH,
    SessionLocal,
    _text_sql_is_proven_read_only,
    configure_sqlite_connection,
    engine,
    release_clean_session_transaction,
    run_session_phase,
    run_session_phase_async,
    session_factory_from_session,
    sqlite_connect_args_for_url,
    sqlite_path_from_database_url,
)


def get_db():
    """兼容依赖注入入口；保留 façade 上 Session factory 的可替换语义。"""

    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def init_db() -> None:
    """兼容初始化入口；迁移与建表始终使用同一组 façade 快照。"""

    db_path = sqlite_path_from_database_url(DATABASE_URL)
    if db_path:
        os.makedirs(os.path.dirname(db_path), exist_ok=True)
    else:
        os.makedirs(DB_DIR, exist_ok=True)

    from core.schema_migrations import run_schema_migrations

    run_schema_migrations(engine, db_path=db_path)
    Base.metadata.create_all(bind=engine)


__all__ = [
    "AdminAuditLog",
    "AdminIdempotencyRecord",
    "AgentRun",
    "Asset",
    "Base",
    "ChatDeliveryOutbox",
    "ChatLog",
    "ChatStreamConfig",
    "ContentBlockRule",
    "ConversationBlock",
    "ConversationBlockEpisode",
    "ConversationTurn",
    "DATABASE_URL",
    "DB_DIR",
    "DB_PATH",
    "EvalCandidate",
    "EvalRun",
    "EvalRunResult",
    "EvalSampleCursor",
    "ExpressionMemory",
    "GroupLearningCandidate",
    "GroupLearningEvidence",
    "GroupLearningRun",
    "GroupLearningSchedule",
    "GroupLearningStreamState",
    "GroupMemory",
    "InboundMessageClaim",
    "JargonMemory",
    "KnowledgeChunk",
    "KnowledgeDocument",
    "KnowledgeSource",
    "LLMApiRequestLog",
    "MemoryCleanupRun",
    "MemoryDigest",
    "MemoryDigestJob",
    "McpConfigurationStateRow",
    "McpDiagnosticRow",
    "McpSecretRow",
    "McpServerRow",
    "OutboundDeliveryAttempt",
    "OutboundDeliveryCircuit",
    "OutboundDeliveryControl",
    "OutboundDeliveryOutbox",
    "OutboundGenerationAttempt",
    "OutboundRun",
    "Persona",
    "PersonaBehavior",
    "PersonaFact",
    "ProactiveOutreachLease",
    "ProactiveOutreachLog",
    "PromptFileVersion",
    "PromptRenderLog",
    "RagDebugRun",
    "ReplyContractCheckLog",
    "ReplyEvalCase",
    "ReplyEvalResult",
    "ReplyEvalRun",
    "RollingSessionSummary",
    "RuntimeTelemetryEvent",
    "RuntimeToolDecision",
    "RunLedgerErasureAuthorization",
    "RunLedgerErasureReceipt",
    "RunLedgerEventRow",
    "RunLedgerLegalHold",
    "RunLedgerStreamHead",
    "RunCheckpointRow",
    "RunRecoveryOperation",
    "RunSideEffectReceipt",
    "RunTaskControl",
    "SANDBOX_EXECUTION_PROFILES",
    "SANDBOX_LEASE_NONTERMINAL_STATUSES",
    "SANDBOX_LEASE_STATUSES",
    "SANDBOX_LEASE_TERMINAL_STATUSES",
    "SandboxAccessGrant",
    "SandboxAdminOperation",
    "SandboxControllerState",
    "SandboxLease",
    "SandboxProjectSequence",
    "SandboxRun",
    "ScheduledTask",
    "ScheduledTaskExecution",
    "ScheduledTaskOwnerLease",
    "ScheduledTaskStepAttempt",
    "SemanticIndexItem",
    "SemanticIndexJob",
    "SensitiveData",
    "SessionLocal",
    "SessionSummaryJob",
    "SessionGoalEventRow",
    "SessionGoalRow",
    "SessionPlanAssetRow",
    "SkillBindingRow",
    "SkillEvaluationRow",
    "SkillInvocationRow",
    "SkillLifecycleEventRow",
    "SkillPackageFileRow",
    "SkillPackageRow",
    "StickerDuplicateCandidate",
    "StickerMemory",
    "SystemPrompt",
    "SystemSetting",
    "ToolCall",
    "ToolOverride",
    "User",
    "UserBlockRule",
    "WebSearchProviderUsage",
    "Workspace",
    "WorkspaceAsset",
    "WorkspaceMaintenanceState",
    "WorkspaceQuotaBinding",
    "WorkspaceRuntimeQuotaBinding",
    "_text_sql_is_proven_read_only",
    "configure_sqlite_connection",
    "engine",
    "get_db",
    "init_db",
    "release_clean_session_transaction",
    "run_session_phase",
    "run_session_phase_async",
    "session_factory_from_session",
    "sqlite_connect_args_for_url",
    "sqlite_path_from_database_url",
]
