from __future__ import annotations

MIN_INTERVAL = 15
MAX_PENDING = 5
MAX_WAIT_SEC = 60
MAX_RETRIES = 3
MAX_AGE_SEC = 120
IDLE_CLEANUP_SEC = 600
BOT_REPLY_COOLDOWN_SEC = 30
TIMING_WAIT_DELAY_MIN = 3
TIMING_WAIT_DELAY_MAX = 15
LINGER_TIMEOUT_SECONDS = 180
LINGER_MAX_MESSAGES = 3
LINGER_BASE_WEIGHT = 0.70
LINGER_MIN_INTERVAL_SECS = 10
BOT_FOLLOWUP_WINDOW_SEC = LINGER_TIMEOUT_SECONDS
_DIRECT_TRIGGERS = {"at_bot", "reply_to_bot", "bot_name_mentioned", "direct_call", "mentioned"}
_COOLDOWN_BYPASS_TRIGGERS = _DIRECT_TRIGGERS | {"recent_bot_followup"}
_DIRECTED_SUPPRESS_BYPASS_TRIGGERS = _DIRECT_TRIGGERS | {"recent_bot_followup"}
