"""Agent Skills 规范兼容与受管生命周期公开接口。"""

from core.skills.contracts import (
    ParsedSkillBundle,
    RuntimeSkillLock,
    RuntimeSkillLockEntry,
    SkillBundleFile,
    SkillContractError,
    SkillScope,
    SkillScopeTarget,
    normalize_semver,
    normalize_skill_name,
    parse_skill_bundle,
    render_skill_catalog,
    semver_key,
    skill_scope_priority,
)
from core.skills.service import (
    LoadedSkillContent,
    SkillBindingSnapshot,
    SkillLifecycleError,
    SkillLifecycleService,
    SkillNotFoundError,
    SkillVersionConflictError,
    SkillVersionSnapshot,
)
from core.skills.provider import (
    BundledSkillCatalog,
    SkillResolutionContext,
    SqlAlchemySkillProvider,
    default_bundled_skill_catalog,
    runtime_skill_targets,
)
from core.skills.discovery import (
    SKILL_DESCRIPTION_INDEX_VERSION,
    SKILL_DESCRIPTION_SOURCE_TYPE,
    SkillRegistryDescriptor,
    SkillSelectionResult,
    SkillSelectionScore,
    build_skill_registry,
    select_skills_for_query,
    synchronize_skill_description_index,
)
from core.skills.governance import (
    SkillGovernanceService,
    SkillVersionGovernanceSnapshot,
)


__all__ = [
    "BundledSkillCatalog",
    "ParsedSkillBundle",
    "LoadedSkillContent",
    "RuntimeSkillLock",
    "RuntimeSkillLockEntry",
    "SkillBundleFile",
    "SkillBindingSnapshot",
    "SkillContractError",
    "SkillGovernanceService",
    "SkillScope",
    "SkillScopeTarget",
    "SkillLifecycleError",
    "SkillLifecycleService",
    "SkillNotFoundError",
    "SkillResolutionContext",
    "SkillVersionConflictError",
    "SkillVersionGovernanceSnapshot",
    "SkillVersionSnapshot",
    "SqlAlchemySkillProvider",
    "SKILL_DESCRIPTION_INDEX_VERSION",
    "SKILL_DESCRIPTION_SOURCE_TYPE",
    "SkillRegistryDescriptor",
    "SkillSelectionResult",
    "SkillSelectionScore",
    "build_skill_registry",
    "default_bundled_skill_catalog",
    "normalize_semver",
    "normalize_skill_name",
    "parse_skill_bundle",
    "render_skill_catalog",
    "select_skills_for_query",
    "synchronize_skill_description_index",
    "runtime_skill_targets",
    "semver_key",
    "skill_scope_priority",
]
