"""数据库 Port、SQLAlchemy Adapter 与 Unit of Work。"""

from core.db.base import Base
from core.db.adapter import (
    SqlAlchemyChatPersistenceRepository,
    SqlAlchemyPersonaFactRepository,
    chat_persistence_repository,
    persona_fact_repository,
)
from core.db.contracts import (
    ChatPersistenceRepositoryPort,
    PersonaFactRepositoryPort,
    TransactionPort,
)
from core.db.uow import UnitOfWork
from core.db.models import (
    ChatLog,
    ChatDeliveryOutbox,
    ConversationTurn,
    InboundMessageClaim,
    MemoryDigest,
    MemoryDigestJob,
    OutboundDeliveryAttempt,
    OutboundDeliveryCircuit,
    OutboundDeliveryControl,
    OutboundDeliveryOutbox,
    OutboundGenerationAttempt,
    OutboundRun,
    Persona,
    PersonaBehavior,
    PersonaFact,
    ProactiveOutreachLease,
    ProactiveOutreachLog,
    SensitiveData,
    RollingSessionSummary,
    SessionSummaryJob,
    ScheduledTask,
    SystemPrompt,
    User,
)

__all__ = [
    "Base",
    "ChatLog",
    "ChatDeliveryOutbox",
    "ChatPersistenceRepositoryPort",
    "ConversationTurn",
    "InboundMessageClaim",
    "MemoryDigest",
    "MemoryDigestJob",
    "OutboundDeliveryAttempt",
    "OutboundDeliveryCircuit",
    "OutboundDeliveryControl",
    "OutboundDeliveryOutbox",
    "OutboundGenerationAttempt",
    "OutboundRun",
    "Persona",
    "PersonaBehavior",
    "PersonaFact",
    "ProactiveOutreachLease",
    "ProactiveOutreachLog",
    "PersonaFactRepositoryPort",
    "SensitiveData",
    "RollingSessionSummary",
    "SessionSummaryJob",
    "ScheduledTask",
    "SqlAlchemyChatPersistenceRepository",
    "SqlAlchemyPersonaFactRepository",
    "SystemPrompt",
    "TransactionPort",
    "UnitOfWork",
    "User",
    "chat_persistence_repository",
    "persona_fact_repository",
]
