"""模型供应商 Port、描述符与不可变注册表。"""

from core.model_provider.contracts import (
    AsyncModelCompletionPort,
    ModelProviderPort,
    ModelProviderRequest,
    ModelProviderResponse,
    ProviderAvailability,
    ProviderCapability,
    ProviderDescriptor,
    ProviderRequestProtocol,
    SyncModelCompletionPort,
)
from core.model_provider.chat_runtime import (
    ChatCompletionPort,
    ChatCompletionRequest,
    ChatCompletionRuntime,
    ChatCompletionRuntimeState,
    ChatCompletionRuntimeUnavailableError,
    RuntimeBoundChatCompletionPort,
)
from core.model_provider.diagnostics import (
    ProviderDiagnosticCheck,
    ProviderDiagnosticLayer,
    ProviderDiagnosticReport,
    ProviderDiagnosticStatus,
    ProviderErrorCategory,
    classify_provider_error,
)
from core.model_provider.catalog_runtime import (
    ModelCatalogRuntime,
    ModelCatalogRuntimeState,
    ModelCatalogWriterPort,
)
from core.model_provider.decision_runtime import (
    DecisionModelPort,
    DecisionModelRuntime,
    DecisionModelRuntimeState,
)
from core.model_provider.registry import (
    DuplicateProviderError,
    ModelProviderRegistry,
    OverridePolicy,
    ProviderCapabilityError,
    ProviderNotFoundError,
    ProviderRegistryFrozenError,
    ProviderUnavailableError,
)
from core.model_provider.route_plan import ReplyRoutePlan
from core.model_provider.route_registry import (
    MODEL_ROUTE_REGISTRY,
    ModelRouteDescriptor,
    ModelRouteDescriptorRegistry,
    ModelRouteError,
    ModelRouteExecutionMode,
    ModelRouteLifecycle,
    ModelRouteNotFoundError,
    ModelRouteSlo,
    ModelRouteSloStatus,
    get_model_route_descriptor,
    list_model_route_descriptors,
    model_route_registry_metadata,
    model_route_registry_snapshot,
    require_model_route_descriptor,
    resolve_model_route_key,
    validate_model_route_task_contracts,
)

__all__ = [
    "ChatCompletionPort",
    "ChatCompletionRequest",
    "ChatCompletionRuntime",
    "ChatCompletionRuntimeState",
    "ChatCompletionRuntimeUnavailableError",
    "DecisionModelPort",
    "DecisionModelRuntime",
    "DecisionModelRuntimeState",
    "ModelCatalogRuntime",
    "ModelCatalogRuntimeState",
    "ModelCatalogWriterPort",
    "DuplicateProviderError",
    "AsyncModelCompletionPort",
    "ModelProviderPort",
    "ModelProviderRegistry",
    "ModelProviderRequest",
    "ModelProviderResponse",
    "MODEL_ROUTE_REGISTRY",
    "ModelRouteDescriptor",
    "ModelRouteDescriptorRegistry",
    "ModelRouteError",
    "ModelRouteExecutionMode",
    "ModelRouteLifecycle",
    "ModelRouteNotFoundError",
    "ModelRouteSlo",
    "ModelRouteSloStatus",
    "OverridePolicy",
    "ProviderAvailability",
    "ProviderDiagnosticCheck",
    "ProviderDiagnosticLayer",
    "ProviderDiagnosticReport",
    "ProviderDiagnosticStatus",
    "ProviderErrorCategory",
    "ProviderCapability",
    "ProviderCapabilityError",
    "ProviderDescriptor",
    "ProviderRequestProtocol",
    "ProviderNotFoundError",
    "ProviderRegistryFrozenError",
    "ProviderUnavailableError",
    "ReplyRoutePlan",
    "RuntimeBoundChatCompletionPort",
    "SyncModelCompletionPort",
    "get_model_route_descriptor",
    "list_model_route_descriptors",
    "model_route_registry_metadata",
    "model_route_registry_snapshot",
    "require_model_route_descriptor",
    "resolve_model_route_key",
    "validate_model_route_task_contracts",
    "classify_provider_error",
]
